#!/usr/bin/env python3
"""Generate repository-local Agent Skills adapters from canonical skills.

The workflow body remains canonical in ``10_Agents/skills``.  This tool emits
small, plain-text discovery adapters for hosts that scan ``.agents/skills``
or ``.claude/skills``.  It is deliberately stdlib-only and deterministic.

Usage:
    python3 10_Agents/tools/skill_adapters/gen_skill_adapters.py
    python3 10_Agents/tools/skill_adapters/gen_skill_adapters.py --check
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import stat
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path


ADAPTER_VERSION = 2
GENERATOR_ID = f"second-brain-skill-adapter/v{ADAPTER_VERSION}"
GENERATED_MARKER = f"<!-- generated by {GENERATOR_ID}; do not edit -->"
CHECKSUM_SENTINEL = "0" * 64
OUTPUT_ROOTS = (Path(".agents/skills"), Path(".claude/skills"))
CANONICAL_ROOT = Path("10_Agents/skills")
MAX_SKILL_NAME_LENGTH = 64
MAX_SKILL_DESCRIPTION_LENGTH = 1024
SKILL_NAME_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
TOP_LEVEL_SCALAR_RE = re.compile(r"^([A-Za-z0-9_-]+):(?:[ \t]+(.*))?$")
YAML_NON_STRING_RE = re.compile(
    r"^(?:"
    r"~|null|true|false|yes|no|on|off|"
    r"[-+]?(?:[0-9][0-9_]*|0[xX][0-9a-fA-F_]+|0[oO][0-7_]+|0[bB][01_]+)|"
    r"[-+]?[0-9][0-9_]*(?::[0-5]?[0-9])+(?:\.[0-9_]*)?|"
    r"[-+]?(?:[0-9][0-9_]*\.[0-9_]*|\.[0-9][0-9_]*|[0-9][0-9_]*[eE][-+]?[0-9]+)|"
    r"[-+]?\.(?:inf|nan)|"
    r"\[.*\]|\{.*\}"
    r")$",
    re.IGNORECASE,
)
YAML_TIMESTAMP_RE = re.compile(
    r"^[0-9]{4}-[0-9]{1,2}-[0-9]{1,2}"
    r"(?:[Tt]|[ \t]+[0-9])?"
    r"(?:[0-9:.,+\-Zz \t]*)$"
)


class AdapterError(ValueError):
    """A deterministic catalog or filesystem contract violation."""


@dataclass(frozen=True)
class Skill:
    name: str
    description: str
    source: Path


def require_case_unique(names: list[str], *, label: str) -> None:
    seen: dict[str, str] = {}
    for name in names:
        folded = name.casefold()
        if folded in seen:
            raise AdapterError(f"case-colliding {label}: {seen[folded]} and {name}")
        seen[folded] = name


def _strip_yaml_comment(value: str) -> str:
    """Remove a plain-scalar YAML comment without treating quoted # as one."""
    quote: str | None = None
    index = 0
    while index < len(value):
        character = value[index]
        if quote == '"':
            if character == "\\":
                index += 2
                continue
            if character == '"':
                quote = None
        elif quote == "'":
            if character == "'":
                if index + 1 < len(value) and value[index + 1] == "'":
                    index += 2
                    continue
                quote = None
        elif character in {'"', "'"}:
            quote = character
        elif character == "#" and (index == 0 or value[index - 1].isspace()):
            return value[:index].rstrip()
        index += 1
    return value.rstrip()


def _scalar(value: str, *, path: Path, key: str) -> str:
    value = _strip_yaml_comment(value.strip())
    if not value:
        raise AdapterError(f"{path}: missing scalar value for {key}")
    if value.startswith(("|", ">")):
        raise AdapterError(
            f"{path}: YAML block scalars are unsupported for discovery field {key}"
        )
    if value.startswith('"'):
        try:
            parsed = json.loads(value)
        except json.JSONDecodeError as exc:
            raise AdapterError(f"{path}: invalid quoted {key}: {exc}") from exc
        if not isinstance(parsed, str):
            raise AdapterError(f"{path}: {key} must be a string")
        return parsed
    if value.startswith("'"):
        if len(value) < 2 or not value.endswith("'"):
            raise AdapterError(f"{path}: invalid single-quoted {key}")
        return value[1:-1].replace("''", "'")
    if (
        YAML_NON_STRING_RE.fullmatch(value)
        or YAML_TIMESTAMP_RE.fullmatch(value)
        or value.startswith(("- ", "!", "&", "*"))
    ):
        raise AdapterError(
            f"{path}: unquoted {key} looks like a non-string YAML value; quote it"
        )
    return value


def read_metadata(path: Path) -> tuple[str, str]:
    """Read the two Agent Skills discovery fields from a SKILL.md."""
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as exc:
        raise AdapterError(f"cannot read {path}: {exc}") from exc
    lines = text.splitlines()
    if not lines or lines[0] != "---":
        raise AdapterError(f"{path}: SKILL.md must start with YAML frontmatter")
    try:
        end = lines.index("---", 1)
    except ValueError as exc:
        raise AdapterError(f"{path}: unterminated YAML frontmatter") from exc
    values: dict[str, str] = {}
    counts: dict[str, int] = {}
    for line in lines[1:end]:
        if line.startswith((" ", "\t")):
            continue
        match = TOP_LEVEL_SCALAR_RE.match(line)
        if not match or match.group(1) not in {"name", "description"}:
            continue
        key = match.group(1)
        counts[key] = counts.get(key, 0) + 1
        values[key] = _scalar(match.group(2) or "", path=path, key=key)
    for key in ("name", "description"):
        if counts.get(key) != 1:
            raise AdapterError(
                f"{path}: expected exactly one top-level {key}, found {counts.get(key, 0)}"
            )
    return values["name"], values["description"]


def _require_nonsymlink_ancestors(repo: Path, rel: Path) -> Path:
    current = repo
    for part in rel.parts:
        current = current / part
        try:
            mode = current.lstat().st_mode
        except OSError as exc:
            raise AdapterError(f"missing canonical path component: {current.relative_to(repo)}") from exc
        if stat.S_ISLNK(mode):
            raise AdapterError(f"symlinked canonical path component: {current.relative_to(repo)}")
        if not stat.S_ISDIR(mode):
            raise AdapterError(f"non-directory canonical path component: {current.relative_to(repo)}")
    return current


def catalog(repo: Path) -> list[Skill]:
    root = _require_nonsymlink_ancestors(repo, CANONICAL_ROOT)
    skills: list[Skill] = []
    names_seen: dict[str, str] = {}
    children = [
        child
        for child in sorted(root.iterdir(), key=lambda p: (p.name.casefold(), p.name))
        if child.is_dir() and not child.name.startswith(".")
    ]
    require_case_unique([child.name for child in children], label="skill directories")
    for child in children:
        if child.is_symlink():
            raise AdapterError(f"symlinked canonical skill directory: {child.relative_to(repo)}")
    for child in children:
        source = child / "SKILL.md"
        if not source.is_file() or source.is_symlink():
            raise AdapterError(f"{source.relative_to(repo)}: missing or symlinked SKILL.md")
        name, description = read_metadata(source)
        if not SKILL_NAME_RE.fullmatch(name):
            raise AdapterError(f"{source.relative_to(repo)}: unsafe skill name {name!r}")
        if len(name) > MAX_SKILL_NAME_LENGTH:
            raise AdapterError(
                f"{source.relative_to(repo)}: skill name exceeds {MAX_SKILL_NAME_LENGTH} characters"
            )
        if not description.strip():
            raise AdapterError(f"{source.relative_to(repo)}: skill description must not be blank")
        if len(description) > MAX_SKILL_DESCRIPTION_LENGTH:
            raise AdapterError(
                f"{source.relative_to(repo)}: skill description exceeds "
                f"{MAX_SKILL_DESCRIPTION_LENGTH} characters"
            )
        if name != child.name:
            raise AdapterError(
                f"{source.relative_to(repo)}: metadata name {name!r} must equal directory {child.name!r}"
            )
        folded_name = name.casefold()
        if folded_name in names_seen:
            raise AdapterError(
                f"metadata name collision: {names_seen[folded_name]} and {name}"
            )
        names_seen[folded_name] = name
        skills.append(Skill(name=name, description=description, source=source))
    if not skills:
        raise AdapterError(f"no canonical skills found under {CANONICAL_ROOT}")
    return skills


def _render_v2(name_value: str, description_value: str, checksum: str) -> bytes:
    name = json.dumps(name_value, ensure_ascii=False)
    description = json.dumps(description_value, ensure_ascii=False)
    canonical = f"../../../{CANONICAL_ROOT.as_posix()}/{name_value}/SKILL.md"
    text = f"""---
name: {name}
description: {description}
metadata:
  adapter-version: {json.dumps(str(ADAPTER_VERSION))}
  canonical-source: {json.dumps(canonical)}
  content-sha256: {json.dumps(checksum)}
---

{GENERATED_MARKER}

# {name_value}

This is a repository-discovery adapter. Before taking any task action, read
`{canonical}` completely and follow it as the sole workflow authority. Resolve
that path relative to this adapter. Do not treat this adapter as a copy of the
workflow and do not continue if the canonical file is missing.
"""
    return text.encode("utf-8")


def render(skill: Skill) -> bytes:
    unsigned = _render_v2(skill.name, skill.description, CHECKSUM_SENTINEL)
    checksum = hashlib.sha256(unsigned).hexdigest()
    return _render_v2(skill.name, skill.description, checksum)


def _render_v1(name_value: str, description_value: str, *, quoted_version: bool) -> bytes:
    name = json.dumps(name_value, ensure_ascii=False)
    description = json.dumps(description_value, ensure_ascii=False)
    canonical = f"../../../{CANONICAL_ROOT.as_posix()}/{name_value}/SKILL.md"
    version = json.dumps("1") if quoted_version else "1"
    text = f"""---
name: {name}
description: {description}
metadata:
  adapter-version: {version}
  canonical-source: {json.dumps(canonical)}
---

<!-- generated by second-brain-skill-adapter/v1; do not edit -->

# {name_value}

This is a repository-discovery adapter. Before taking any task action, read
`{canonical}` completely and follow it as the sole workflow authority. Resolve
that path relative to this adapter. Do not treat this adapter as a copy of the
workflow and do not continue if the canonical file is missing.
"""
    return text.encode("utf-8")


def expected_files(repo: Path) -> dict[Path, bytes]:
    expected: dict[Path, bytes] = {}
    for skill in catalog(repo):
        body = render(skill)
        for output_root in OUTPUT_ROOTS:
            expected[output_root / skill.name / "SKILL.md"] = body
    return expected


def _walk_output(repo: Path) -> tuple[set[Path], list[str]]:
    files: set[Path] = set()
    findings: list[str] = []
    for output_root in OUTPUT_ROOTS:
        root = repo / output_root
        current = repo
        unsafe_ancestor = False
        for part in output_root.parts:
            current = current / part
            if current.is_symlink():
                findings.append(f"symlink:{current.relative_to(repo).as_posix()}")
                unsafe_ancestor = True
                break
        if unsafe_ancestor:
            continue
        if not root.exists():
            continue
        if root.is_symlink() or not root.is_dir():
            findings.append(f"symlink-or-nondirectory:{output_root.as_posix()}")
            continue
        root_names: dict[str, str] = {}
        for child in root.iterdir():
            if child.is_dir():
                folded = child.name.casefold()
                if folded in root_names:
                    findings.append(
                        f"case-collision:{output_root.as_posix()}:{root_names[folded]}:{child.name}"
                    )
                root_names[folded] = child.name
        for parent, dirs, names in os.walk(root, followlinks=False):
            parent_path = Path(parent)
            for name in list(dirs):
                candidate = parent_path / name
                rel = candidate.relative_to(repo)
                if candidate.is_symlink():
                    findings.append(f"symlink:{rel.as_posix()}")
                    dirs.remove(name)
            for name in names:
                candidate = parent_path / name
                rel = candidate.relative_to(repo)
                if candidate.is_symlink():
                    findings.append(f"symlink:{rel.as_posix()}")
                else:
                    files.add(rel)
    return files, findings


def check(repo: Path) -> list[str]:
    expected = expected_files(repo)
    actual, findings = _walk_output(repo)
    for rel, wanted in expected.items():
        path = repo / rel
        if rel not in actual:
            findings.append(f"missing:{rel.as_posix()}")
            continue
        try:
            got = path.read_bytes()
        except OSError as exc:
            findings.append(f"unreadable:{rel.as_posix()}:{exc}")
            continue
        if got != wanted:
            findings.append(f"drift:{rel.as_posix()}")
    for rel in sorted(actual - set(expected), key=lambda p: p.as_posix()):
        findings.append(f"extra:{rel.as_posix()}")
    return sorted(set(findings))


def _atomic_write(path: Path, body: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "wb") as handle:
            handle.write(body)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(tmp_name, path)
    finally:
        try:
            os.unlink(tmp_name)
        except FileNotFoundError:
            pass


def _owned_adapter(path: Path, rel: Path) -> bool:
    """Authenticate the complete adapter bytes, including legacy v1 output."""
    if len(rel.parts) != 4 or rel.parts[-1] != "SKILL.md":
        return False
    output_root = Path(*rel.parts[:2])
    if output_root not in OUTPUT_ROOTS:
        return False
    directory_name = rel.parts[2]
    try:
        body = path.read_bytes()
        lines = body.decode("utf-8").splitlines()
    except (OSError, UnicodeDecodeError):
        return False
    if len(lines) < 7:
        return False
    try:
        name = json.loads(lines[1].removeprefix("name: "))
        description = json.loads(lines[2].removeprefix("description: "))
    except (json.JSONDecodeError, TypeError):
        return False
    if name != directory_name or not isinstance(description, str):
        return False
    if lines[4] == f'  adapter-version: "{ADAPTER_VERSION}"':
        unsigned = _render_v2(name, description, CHECKSUM_SENTINEL)
        expected = _render_v2(name, description, hashlib.sha256(unsigned).hexdigest())
        return body == expected
    if lines[4] in {'  adapter-version: "1"', "  adapter-version: 1"}:
        return body in {
            _render_v1(name, description, quoted_version=True),
            _render_v1(name, description, quoted_version=False),
        }
    return False


@dataclass(frozen=True)
class Preflight:
    expected: dict[Path, bytes]
    actual: frozenset[Path]
    root_identities: tuple[tuple[Path, tuple[int, int] | None], ...]


def preflight(repo: Path) -> Preflight:
    """Validate every input/output ownership boundary without mutating."""
    expected = expected_files(repo)
    actual, unsafe = _walk_output(repo)
    if unsafe:
        raise AdapterError("refusing unsafe output tree: " + ", ".join(sorted(unsafe)))
    foreign = [
        rel
        for rel in sorted(actual, key=lambda p: p.as_posix())
        if not _owned_adapter(repo / rel, rel)
    ]
    for rel in sorted(expected, key=lambda p: p.as_posix()):
        path = repo / rel
        try:
            path.lstat()
        except FileNotFoundError:
            continue
        except OSError as exc:
            raise AdapterError(f"cannot inspect expected adapter {rel}: {exc}") from exc
        if rel not in actual:
            foreign.append(rel)
    if foreign:
        raise AdapterError(
            "refusing foreign adapter path(s): "
            + ", ".join(rel.as_posix() for rel in sorted(set(foreign)))
        )
    identities: list[tuple[Path, tuple[int, int] | None]] = []
    for root in OUTPUT_ROOTS:
        try:
            info = (repo / root).lstat()
        except FileNotFoundError:
            identities.append((root, None))
        except OSError as exc:
            raise AdapterError(f"cannot inspect output root {root}: {exc}") from exc
        else:
            identities.append((root, (info.st_dev, info.st_ino)))
    return Preflight(expected, frozenset(actual), tuple(identities))


def _secure_open_parent(repo_fd: int, name: str) -> tuple[int, bool]:
    flags = os.O_RDONLY | getattr(os, "O_DIRECTORY", 0) | getattr(os, "O_NOFOLLOW", 0)
    created = False
    try:
        before = os.stat(name, dir_fd=repo_fd, follow_symlinks=False)
    except FileNotFoundError:
        os.mkdir(name, dir_fd=repo_fd)
        created = True
        before = os.stat(name, dir_fd=repo_fd, follow_symlinks=False)
    except OSError as exc:
        raise AdapterError(f"cannot inspect output parent {name}: {exc}") from exc
    if not stat.S_ISDIR(before.st_mode):
        raise AdapterError(f"unsafe output parent {name}: expected a real directory")
    try:
        descriptor = os.open(name, flags, dir_fd=repo_fd)
    except OSError as exc:
        raise AdapterError(f"cannot securely open output parent {name}: {exc}") from exc
    after = os.fstat(descriptor)
    if (before.st_dev, before.st_ino) != (after.st_dev, after.st_ino):
        os.close(descriptor)
        raise AdapterError(f"output parent changed while opening: {name}")
    return descriptor, created


def _root_identity(prepared: Preflight, root: Path) -> tuple[int, int] | None:
    return dict(prepared.root_identities)[root]


def _verify_child_identity(parent_fd: int, child: str, expected: tuple[int, int] | None) -> None:
    try:
        current = os.stat(child, dir_fd=parent_fd, follow_symlinks=False)
    except FileNotFoundError:
        if expected is None:
            return
        raise AdapterError(f"output root disappeared after preflight: {child}")
    except OSError as exc:
        raise AdapterError(f"cannot inspect output root before swap: {child}: {exc}") from exc
    if expected is None:
        raise AdapterError(f"output root appeared after preflight: {child}")
    if not stat.S_ISDIR(current.st_mode) or (current.st_dev, current.st_ino) != expected:
        raise AdapterError(f"output root changed after preflight: {child}")


def generate(repo: Path) -> None:
    repo = repo.resolve()
    prepared = preflight(repo)
    transaction = Path(tempfile.mkdtemp(prefix=".skill-adapter-transaction-", dir=repo))
    repo_fd = -1
    transaction_fd = -1
    swaps: list[dict[str, object]] = []
    created_parents: list[tuple[str, int]] = []
    opened_parent_fds: set[int] = set()
    try:
        stage_names: dict[Path, str] = {}
        for index, root in enumerate(OUTPUT_ROOTS):
            stage_name = f"stage-{index}"
            stage_names[root] = stage_name
            (transaction / stage_name).mkdir()
        for rel, body in sorted(prepared.expected.items(), key=lambda item: item[0].as_posix()):
            root = next(root for root in OUTPUT_ROOTS if rel.is_relative_to(root))
            target = transaction / stage_names[root] / rel.relative_to(root)
            _atomic_write(target, body)

        # Refuse any catalog/output change that happened while staging.  The
        # final swaps then use no-follow directory descriptors, so a later
        # parent replacement cannot redirect writes outside the repository.
        if preflight(repo) != prepared:
            raise AdapterError("skill adapter inputs or outputs changed after preflight")

        flags = os.O_RDONLY | getattr(os, "O_DIRECTORY", 0) | getattr(os, "O_NOFOLLOW", 0)
        repo_fd = os.open(repo, flags)
        transaction_fd = os.open(transaction, flags)
        for index, root in enumerate(OUTPUT_ROOTS):
            parent_name, child_name = root.parts
            parent_fd, created = _secure_open_parent(repo_fd, parent_name)
            opened_parent_fds.add(parent_fd)
            if created:
                created_parents.append((parent_name, parent_fd))
            expected_identity = _root_identity(prepared, root)
            _verify_child_identity(parent_fd, child_name, expected_identity)
            record: dict[str, object] = {
                "parent_fd": parent_fd,
                "child": child_name,
                "backup": f"backup-{index}",
                "discard": f"discard-{index}",
                "existed": expected_identity is not None,
                "backup_moved": False,
                "installed": False,
            }
            swaps.append(record)

        if preflight(repo) != prepared:
            raise AdapterError("skill adapter tree changed before secure swap")

        for index, root in enumerate(OUTPUT_ROOTS):
            record = swaps[index]
            parent_fd = int(record["parent_fd"])
            child_name = str(record["child"])
            expected_identity = _root_identity(prepared, root)
            _verify_child_identity(parent_fd, child_name, expected_identity)
            if expected_identity is not None:
                os.replace(
                    child_name,
                    record["backup"],
                    src_dir_fd=parent_fd,
                    dst_dir_fd=transaction_fd,
                )
                record["backup_moved"] = True
            os.replace(
                stage_names[root],
                child_name,
                src_dir_fd=transaction_fd,
                dst_dir_fd=parent_fd,
            )
            record["installed"] = True

        findings = check(repo)
        if findings:
            raise AdapterError("post-generation drift: " + ", ".join(findings))
    except BaseException as exc:
        rollback_errors: list[str] = []
        for record in reversed(swaps):
            parent_fd = int(record["parent_fd"])
            try:
                if record["installed"]:
                    os.replace(
                        str(record["child"]),
                        str(record["discard"]),
                        src_dir_fd=parent_fd,
                        dst_dir_fd=transaction_fd,
                    )
                if record["backup_moved"]:
                    os.replace(
                        str(record["backup"]),
                        str(record["child"]),
                        src_dir_fd=transaction_fd,
                        dst_dir_fd=parent_fd,
                    )
            except OSError as rollback_exc:
                rollback_errors.append(str(rollback_exc))
        detail = f"; rollback failures: {rollback_errors}" if rollback_errors else ""
        if isinstance(exc, AdapterError):
            raise AdapterError(f"{exc}{detail}") from exc
        if isinstance(exc, (KeyboardInterrupt, SystemExit)) and not rollback_errors:
            raise
        raise AdapterError(f"transactional generation failed: {exc}{detail}") from exc
    finally:
        for descriptor in opened_parent_fds:
            try:
                os.close(descriptor)
            except OSError:
                pass
        if transaction_fd >= 0:
            os.close(transaction_fd)
        for parent_name, _descriptor in created_parents:
            # Failed transactions that started with no output parent should
            # leave no empty scaffolding behind.
            if not (repo / parent_name / "skills").exists():
                try:
                    os.rmdir(parent_name, dir_fd=repo_fd)
                except OSError:
                    pass
        if repo_fd >= 0:
            os.close(repo_fd)
        shutil.rmtree(transaction, ignore_errors=True)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--repo", type=Path, default=Path(__file__).resolve().parents[3])
    parser.add_argument("--check", action="store_true", help="report drift without writing")
    parser.add_argument(
        "--preflight",
        action="store_true",
        help="validate catalog, paths, and complete-file ownership without writing",
    )
    args = parser.parse_args(argv)
    if args.check and args.preflight:
        parser.error("--check and --preflight are mutually exclusive")
    repo = args.repo.resolve()
    try:
        if args.preflight:
            prepared = preflight(repo)
            print(f"skill-adapters: preflight OK ({len(prepared.expected)} adapters)")
            return 0
        if args.check:
            findings = check(repo)
            if findings:
                for finding in findings:
                    print(f"skill-adapters: {finding}", file=sys.stderr)
                return 1
            print("skill-adapters: fresh")
            return 0
        generate(repo)
        findings = check(repo)
        if findings:
            raise AdapterError("post-generation drift: " + ", ".join(findings))
        print(f"skill-adapters: generated {len(expected_files(repo))} adapters")
        return 0
    except AdapterError as exc:
        print(f"skill-adapters: error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
